name: Main

on:
  push:
    branches: [main]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'refs/heads/main') }}

jobs:
  check-workflows:
    name: Check workflows
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download actionlint
        id: download-actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/7fdc9630cc360ea1a469eed64ac6d78caeda1234/scripts/download-actionlint.bash) 1.6.25
        shell: bash
      - name: Check workflow files
        run: ${{ steps.download-actionlint.outputs.executable }} -color
        shell: bash

  lint-build-test:
    name: Lint, build, and test
    needs: check-workflows
    uses: ./.github/workflows/lint-build-test.yml

  is-release:
    name: Determine whether this is a release merge commit
    needs: lint-build-test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    outputs:
      IS_RELEASE: ${{ steps.is-release.outputs.IS_RELEASE }}
    steps:
      - id: is-release
        uses: MetaMask/action-is-release@dc4672b05e3b1d464cdaf783579b04a4e43f8b02
        with:
          commit-starts-with: 'Release v[version]'

  publish-release:
    name: Publish release
    needs: is-release
    if: needs.is-release.outputs.IS_RELEASE == 'true'
    permissions:
      contents: write
    uses: ./.github/workflows/publish-release.yml
    secrets:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

  all-jobs-pass:
    name: All jobs pass
    runs-on: ubuntu-latest
    needs: lint-build-test
    steps:
      - run: echo "Great success!"
